# fly.toml app configuration file generated for invoice-app-gusvianadev on 2023-10-05T22:04:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "invoice-app-gusvianadev"
primary_region = "eze"

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
